---    
- name: Copy config file
  template:
    src: "config.yaml.j2"
    dest: "{{ k3s_config_dir }}/config.yaml"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes