---
k3s_version: v1.22.3+k3s1
k3s_systemd_dir: /etc/systemd/system
k3s_server_location: /var/lib/rancher/k3s
k3s_server_location_node: /var/lib/rancher/k3s/server/node-token
k3s_master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
k3s_token_file: /etc/rancher/node/password
ansible_user: hewson