policy: upsert-only

provider: cloudflare

# extraArgs:
#   |
#   cloudflare-proxied

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token-secret
      key: api-token


