- name: Copy config file
  template:
    src: "config.yaml.j2"
    dest: "{{ k3s_config_dir }}/config.yaml"
    owner: root
    group: root
    mode: 0644
    
- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: "{{ k3s_server_location_node }}"

- name: Register node-token file access mode
  stat:
    path: "{{ k3s_server_location_node }}"
  register: p

- name: Change file access node-token
  file:
    path: "{{ k3s_server_location_node }}"
    mode: "g+rx,o+rx"
    
- name: Read node-token from mastes
  slurp:
    path: "{{ k3s_server_location_node }}"
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: "{{ k3s_server_location_node }}"
    mode: "{{ p.stat.mode }}"
    
- name: fetch config file to user home directory
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    flat: yes

- name: update kubeconfig
  command: >-
    kubectl config set-cluster default
      --server=https://{{ k3s_master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true
  delegate_to: localhost