server:
  enabled: true

  ingress:
    enabled: true
    annotations:
      |
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: cname.hewson.io
    ingressClassName: nginx
    pathType: Prefix
    activeService: true
    hosts:
      - host: vault3.hewson.io
    tls:
      - secretName: vault3.hewson-tls
        hosts:
          - vault3.hewson.io
          
dev:
  enabled: true

