repositories:
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: cert-manager
  url: https://charts.jetstack.io
- name: longhorn
  url: https://charts.longhorn.io

helmDefaults:
  verify: false
  wait: true
  timeout: 600
  atomic: true

# environments:
#   default:

templates:
  default: &default
    chart: '{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}'
    namespace: '{{`{{ .Release.Name }}`}}'
    missingFileHandler: Warn
    values:
    - config/values/{{`{{ .Release.Name }}`}}.yaml

releases:
- name: vault
  chart: hashicorp/vault
  version: 0.19.0
  namespace: vault
  values:
  - config/values/vault.yaml
      

- name: metallb
  version: 0.11.0
  <<: *default

- name: ingress-nginx
  version: 4.0.13
  <<: *default

- name: cert-manager
  version: 1.7.0
  <<: *default

- name: external-dns
  version: 1.7.1
  <<: *default

- name: longhorn
  version: 1.2.4
  <<: *default