repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/

helmDefaults:
  verify: false
  wait: true
  timeout: 600
  atomic: true

environments:
  default:

releases:
  - name: metallb
    namespace: metallb
    chart: bitnami/metallb
    version: 2.6.1
    values:
    - values/metallb.yaml

  # - name: ingress-nginx
  #   namespace: ingress-nginx
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.0.13
  #   condition: ingress-nginx.enabled
  #   values:
  #   - values/ingress-nginx.yaml

  # - name: external-dns
  #   namespace: external-dns
  #   chart: external-dns/external-dns
  #   values: 1.7.1
  #   - values/external-dns.yaml