repositories:
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: cert-manager
  url: https://charts.jetstack.io

helmDefaults:
  verify: false
  wait: true
  timeout: 600
  atomic: true

environments:
  default:

releases:
  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.19.0
    values:
    - values/vault.yaml

  - name: metallb
    namespace: metallb
    chart: metallb/metallb
    version: 0.11.0
    values:
    - values/metallb.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.0.13
    values:
    - values/ingress-nginx.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager 
    version: 1.7.0
    values:
    - values/cert-manager.yaml

  # - name: external-dns
  #   namespace: external-dns
  #   chart: external-dns/external-dns
  #   values: 1.7.1
  #   - values/external-dns.yaml